2019-06-21T11:23:56|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "Microscope_app.py", line 54, in <module>
    app = MicroscopeApp(sys.argv)
  File "C:\Users\lindat18\AppData\Local\Continuum\miniconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\base_app.py", line 340, in __init__
    self.setup_default_ui()
  File "C:\Users\lindat18\AppData\Local\Continuum\miniconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\base_app.py", line 380, in setup_default_ui
    measure.setup_figure()
  File "C:\Users\lindat18\Dropbox\Ginger_Lab\Microscope_App\HW_Picoharp\picoharp_scan.py", line 38, in setup_figure
    picoharp_hw.settings.Tacq.connect_to_widget(tacq_spinBox)
NameError: name 'picoharp_hw' is not defined

