2019-06-20T11:54:24|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "Microscope_app.py", line 43, in <module>
    app = MicroscopeApp(sys.argv)
  File "C:\Users\lindat18\AppData\Local\Continuum\miniconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\base_app.py", line 338, in __init__
    self.setup()
  File "Microscope_app.py", line 27, in setup
    self.add_measurement(OceanOptics_Scan)
  File "C:\Users\lindat18\AppData\Local\Continuum\miniconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\base_app.py", line 690, in add_measurement
    measure = measure(app=self)
  File "C:\Users\lindat18\AppData\Local\Continuum\miniconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\measurement.py", line 93, in __init__
    self.setup()
  File "C:\Users\lindat18\Dropbox\Ginger_Lab\Microscope_App\HW_PI_PiezoStage\OceanOptics_Scan.py", line 8, in setup
    PiezoStageMeasureLive.setup(self)
NameError: name 'PiezoStageMeasureLive' is not defined

